## Appendix A
```{r functions.R}
## ---------------------------
##
## Name: functions.R
##
## Author: Lisa Hu
##
## Purpose: Script contains functions used in the result scripts
##
## Email: l.j.b.hu@st.hanze.nl
##
## ---------------------------

## ---- basic-model
model <- function(t, y, parms){
  # Add water every given days, until day 80
  if(t %% as.numeric(parms["time"]) == 0 && t < 80 && t > 0){
    with(as.list(c(parms, y)), {
      dW <- I # I is the water irrigation
      dC <- 0 # There is no growth on those days
      return( list( c(dW, dC) ) )
    })
  }
  # Else the model runs with the equations
  else{
    with(as.list(c(parms, y)),{
      dW <- (-B * q * W) - (r * C * (1 - ( C/N ) ) * W)
      dC <- (r * C * (1 - ( C/N ) ) * W) + ( (g*q*C*W)/(C+1)*(W+1) ) - o * C
      return( list( c(dW, dC) ) )
    })
  }
}

## ---- Day-night model
day.night_model <- function(t, y, parms){
  # Add water every given days, until day 80
  if(t %% as.numeric(parms["time"]) == 0 && t < 80 && t > 0){
    with( as.list( c(parms, y)), {
      dW <- I * 24 # I is the water irrigation
      # NOTE : x24 because the water amount should not change
      dC <- 0 # There is no growth on those days
      return( list( c(dW, dC) ) )
    })
  }
  # Else the model runs with the equations
  else{
    if(t %% 1 <= 0.25 | t %% 1 >= 0.83){
      # During the night (no sun)
      with( as.list (c(parms, y)), {
        dW <- ((-B * q * W) - (r * C * (1 - ( C/N ) ) * W)) # Normal water drop
        dC <- 0 # No growth
        return( list( c(dW, dC) ) )
        })
    }
    else{
      # During the day (sun)
      with( as.list( c(parms, y)),{
      dW <- ((-B * q * W) - (r * C * (1 - ( C/N ) ) * W))
      dC <- ((r * C * (1 - ( C/N ) ) * W) + ( (g*q*C*W)/(C+1)*(W+1) ) - o * C)
      return( list( c(dW, dC) ) )
      })
    }
  }
}

## ---- water-model
water_model <- function(t, y, parms){
  # Add water every given days, until day 80
  with(as.list(c(parms, y)),{
    dW <- (-B * q * W) - (r * C * (1 - ( C/N ) ) * W)
    dC <- (r * C * (1 - ( C/N ) ) * W) + ( (g*q*C*W)/(C+1)*(W+1) ) - o * C
    dI <- 0
    return( list( c(dW, dC, dI) ) )
  })
}

## Function to create plots
create.plots <- function(plot.values, ref.data, change.data){
  #' plot.values = The column name of the datas
  #' ref.data = The reference data
  #' change.data = The data that contains changed values
  data.names <- names(change.data)
  # Create colours for the different lines (except the reference data)
  colours <- hue_pal()(length(change.data))
  # y.val inserts the plot.value for the corresponding row of data.values
  y.val <- data.values[plot.values,]
  # The plot
  plt <- ggplot(data = ref.data, mapping = aes(x = time, y = !!sym(y.val$name) ) ) +
    # Lines (Reference data stays black)
    geom_line(aes(color = "Reference")) +
    unlist( mapply(function(single.data, data.name)
                        geom_line(data = single.data, aes(color = data.name) ),
                   change.data, data.names ) ) +
    # Labels
    labs(x = "Time", y = y.val$ylabel) +
    theme(legend.position = "bottom") +
    # Line colours
    scale_colour_manual(values = c("black", colours),
                        limits = c("Reference", names(change.data) ) ) +
    # Legend correction
    guides(color = guide_legend(title = ""))
  return(plt)
}

## Labels and titles for according value
data.values <- data.frame(name = c("W", "C"),
                          ylabel = c("W(t)", "C(t)"))
rownames(data.values) <- data.values$name

```

## Appendix B
```{r results1.R}
## ---------------------------
##
## Name: results1.R
##
## Author: Lisa Hu
##
## Purpose: Script creates the first results for the final report
##
## Email: l.j.b.hu@st.hanze.nl
##
## ---------------------------

## ODE values
parameters <- c(q = 0.5, r = 0.043, N = 3000, I = 1,
                B = 0.06, g = 0.001, o = 0.00001, time = 8)
state <- c(W = 0.6, C = 1)
times <- seq(0, 120, by = 1)

## Run the simulations
ref.data <- as.data.frame(ode(times = times, y = state,
                              parms = parameters, func = model, method = "euler"))

## Determine the different q values
q.values <- list("q = 0.1" = 0.1,
                 "q = 1" = 1)

for(i in seq_along(q.values)){
  parameters$q <- q.values[[i]]  # Set new q value
  # Run the simulation and store in q.values
  q.values[[i]] <- as.data.frame(ode(times = times, y = state,
                                     parms = parameters, func = model, method = "euler"))
}

## Simulation for delayed water irrigation (every 16 days)
parameters <- c(q = 0.5, r = 0.043, N = 3000, I = 1,
                B = 0.06, g = 0.001, o = 0.00001, time = 16)

delay.data <- as.data.frame(ode(times = times, y = state, parms = parameters,
                                func = model, method = "euler"))
delay.data <- list("Delayed water irrigation" = delay.data)


## Create the plots
# The model simulation
plt1 <- ggplot(ref.data, mapping = aes(x = time)) +
          # The different lines
          geom_line(mapping = aes(y = W, color = "Water")) +
          geom_line(mapping = aes(y = C, color = "Biomass"), linetype = "dashed") +
          # Labels
          labs(x = "Time", y = "W(t), C(t)") +
          # Line colours
          scale_colour_manual(values = c("blue", "red"),
                              limits = c("Water", "Biomass")) +
          # Make the line of the Biomass a dashed line in the legend
          guides(color = guide_legend(title = "",
                                      override.aes = list(linetype = c(1, 2))))

# Different q values
plt2 <- lapply("C", create.plots, ref.data, q.values)

# Delayed water model
plt3 <- lapply(c("W", "C"), create.plots, ref.data, delay.data)

## Add figure annotation
plot.list <- append(list(plt1), c(plt2, plt3))
plot.tags <- c("(a)", "(b)", "(c)", "(d)")

for(i in seq_along(plot.list)){
  plot.list[[i]] <- plot.list[[i]] + labs(tag = plot.tags[i])
}

## Arrange plots
my.grid <- ggarrange(plotlist = plot.list, ncol = 2, nrow = 2,
                     common.legend = FALSE, legend = "bottom")
## Print plots
print( annotate_figure(my.grid) )

```
## Appendix C
```{r results2.R}
## ---------------------------
##
## Name: results2.R
##
## Author: Lisa Hu
##
## Purpose: Script creates the day/night results for the final report
##
## Email: l.j.b.hu@st.hanze.nl
##
## ---------------------------

## ODE values
parameters <- c(q = 0.5, r = 0.043, N = 3000, I = 1,
                B = 0.06, g = 0.001, o = 0.00001, time = 8)
state <- c(W = 0.6, C = 1)
times <- seq(0, 120, by = 1/24)

## Run the simulations
d.n_data <- as.data.frame(ode(times = times, y = state, parms = parameters,
                              func = day.night_model, method = "euler"))

## Create the plot
ggplot(d.n_data, mapping = aes(x = time)) +
       # The different lines
       geom_line(mapping = aes(y = W, color = "Water")) +
       geom_line(mapping = aes(y = C, color = "Biomass day/night")) + # day/night
       geom_line(mapping = aes(y = C, color = "Reference biomass"),
                 data = ref.data, linetype = "dashed") + # Default model
       # Labels
       labs(x = "Time", y = "W(t), C(t)") +
       # Line colours
       scale_colour_manual(values = c("blue", "red", "black"),
                           limits = c("Water", "Biomass day/night",
                                      "Reference biomass")) +
       guides(color = guide_legend(title = "",
                                   override.aes = list(linetype = c(1, 1, 2)))) +
       # Theme
       theme(legend.position = "bottom")

```
## Appendix D
```{r results3.R}
## ---------------------------
##
## Name: results3.R
##
## Author: Lisa Hu
##
## Purpose: Script creates the results for different days of water irrigation
##
## Email: l.j.b.hu@st.hanze.nl
##
## ---------------------------

## ODE values
parameters <- c(q = 0.5, r = 0.043, N = 3000, I = 1,
                B = 0.06, g = 0.001, o = 0.00001, time = 8) # time = 8 for reference
state <- c(W = 0.6, C = 1)
times <- seq(0, 120, by = 1)

## Run the simulations
ref.data <- as.data.frame(ode(times = times, y = state,
                              parms = parameters, func = model, method = "euler"))

time.values <- list("Every 5 days" = 5,
                    "Every 10 days" = 10,
                    "Every 12 days" = 12)

for(i in seq_along(time.values)){
  parameters$time <- time.values[[i]]  # Set the time value
  # Run the simulation and store in time.values
  time.values[[i]] <- as.data.frame(ode(times = times, y = state,
                              parms = parameters, func = model, method = "euler"))
}

## Create the plots
plts <- lapply(c("W", "C"), create.plots, ref.data, time.values)

## Add the figure annotations
plot.tags <- c("(a)", "(b)")
for(i in seq_along(plts)){
  plts[[i]] <- plts[[i]] + labs(tag = plot.tags[i])
}

## Arrange the plots
my.grid <- ggarrange(plotlist = plts, ncol = 1, nrow = 2,
                     common.legend = FALSE, legend = "bottom")
## Print the plots with a title
print( annotate_figure(my.grid,
                       top = text_grob("Water irrigation on different days") ) )

```
## Appendix E
```{r results4.R}
## ---------------------------
##
## Name: results4.R
##
## Author: Lisa Hu
##
## Purpose: Script adds water to the system when it's 0
##
## Email: l.j.b.hu@st.hanze.nl
##
## ---------------------------

## ODE values
parameters <- c(q = 0.5, r = 0.043, N = 3000, B = 0.06, g = 0.001, o = 0.00001, time = 8)
state <- c(W = 0.6, C = 1, I = 0)
times <- seq(0, 120, by = 1)

## Determine what the root is
root <- function(t, y, parms){
  return(y["W"] - 4e-3)
}

## When root found, execute event
eventfun <- function (t, y, parms){
  y["I"] <- 1
  y["W"] <- y["W"] + y["I"]
  return(y)
}

## Run the simulation with events
sim.data <- ode(times = times, y = state, parms = parameters,
                func = water_model, rootfunc = root,
                events = list(func = eventfun, root = TRUE, terminalroot = 2))
roottimes <- attributes(sim.data)$troot  # Timesteps where root was found
sim.data <- as.data.frame(sim.data)

## Create plot
ggplot(sim.data, mapping = aes(x = time)) +
       # The different lines
       geom_line(mapping = aes(y = W, color = "Water")) +
       geom_line(mapping = aes(y = C, color = "Biomass")) +
       # Vertical lines where root was found
       unlist( mapply( function(x){
         geom_vline(xintercept = x, linetype = "dashed")
                                   }, roottimes) ) +
       # Labels
       labs(x = "Time", y = "W(t), C(t)") +
       # Line colours
       scale_colour_manual(values = c("blue", "red"),
                           limits = c("Water", "Biomass")) +
       # Theme
       theme(legend.position = "bottom")

```
