---
output:
  pdf_document:
    toc: true
    toc_depth: 2
    number_sections: true
    includes:
      before_body: title.tex
      in_header: header.tex
bibliography: references.bib
---
```{r setup, include = FALSE, warning = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(cache = TRUE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(error = FALSE)

BOSS_MODE <- TRUE
source('functions.R', local = knitr::knit_global())
scripts <- c("functions.R", "results1.R", "results2.R")
invisible(lapply(scripts, knitr::read_chunk))

packages <- c("deSolve", "ggplot2", "formatR", "scales", "ggpubr")
invisible(lapply(packages, library, character.only = T))
```

[//]: # (Page 4: Table of Contents)

\newpage

[//]: # (Page 5: Introduction)
\pagenumbering{arabic}
# Introduction


\newpage

[//]: # (Page : Materials & methods)
# Materials and Methods
## Materials


## Methods


\newpage

[//]: # (Page : Results)
# Results


\newpage

[//]: # (Page : Conclusion)
# Conclusion


\newpage

[//]: # (Page : Discussion)
# Discussion


\newpage

[//]: # (Page : References)
# References
```{r references, child = 'references.Rmd'}
```

\newpage

[//]: # (Page : Appendix)
# Appendix
```{r appendix, child = 'appendix.Rmd'}
```
